"""
Task Specification Schemas — orchestration/orchestrator/schemas/task_spec.py
=============================================================================
Defines the structured contract for subtask handoff between
Planner, DAG Scheduler, Executor, and Worker agents.

Resolves Issue #1 (Raw prompt pass-through) and Issue #10 (Flat sequential plan).
"""

from enum import Enum
from typing import List, Dict, Any, Optional
from pydantic import BaseModel, Field


class TaskStatus(str, Enum):
    """Execution lifecycle state of a single subtask."""
    PENDING = "pending"
    IN_PROGRESS = "in_progress"
    COMPLETED = "completed"
    FAILED = "failed"
    SKIPPED = "skipped"


class TaskSpec(BaseModel):
    """
    Atomic unit of work in the execution plan.
    Each TaskSpec represents a single subtask assigned to one worker agent.
    The `depends_on` field enables DAG-based dependency scheduling.
    """
    task_id: str = Field(..., description="Unique subtask identifier, e.g. task_01")
    agent: str = Field(..., description="Name of the registered target worker agent")
    subtask: str = Field(..., description="Detailed instructions for this specific subtask")
    depends_on: List[str] = Field(
        default_factory=list,
        description="IDs of tasks that must complete before this runs (DAG edges)"
    )
    context: Dict[str, Any] = Field(
        default_factory=dict,
        description="Metadata and input context for this subtask"
    )
    status: TaskStatus = Field(
        default=TaskStatus.PENDING,
        description="Current execution state of the subtask"
    )
    result: Optional[str] = Field(
        default=None,
        description="Output content produced by the worker after execution"
    )
    feedback: Optional[str] = Field(
        default=None,
        description="Reviewer feedback if rejected on a prior attempt"
    )
    assigned_tools: List[str] = Field(
        default_factory=list,
        description="Allowed tools for this subtask (e.g. write_file, execute_command)"
    )


class ExecutionPlan(BaseModel):
    """
    A structured execution plan containing a DAG of TaskSpecs.
    Generated by the Planner node and consumed by the DAG Scheduler.
    """
    plan_id: str = Field(..., description="Unique plan identifier")
    goal: str = Field(..., description="High-level goal received from the user")
    tasks: List[TaskSpec] = Field(
        default_factory=list,
        description="Ordered list of TaskSpecs forming the execution DAG"
    )

    def get_task(self, task_id: str) -> Optional[TaskSpec]:
        """Retrieve a TaskSpec by its ID."""
        for t in self.tasks:
            if t.task_id == task_id:
                return t
        return None

    def get_completed_task_ids(self) -> List[str]:
        """Return IDs of all completed tasks."""
        return [t.task_id for t in self.tasks if t.status == TaskStatus.COMPLETED]

    def is_complete(self) -> bool:
        """Returns True if all tasks are completed or skipped."""
        return all(
            t.status in [TaskStatus.COMPLETED, TaskStatus.SKIPPED]
            for t in self.tasks
        )
